#!/bin/bash
if [ `arch` = x86_64 ]
then
	echo Compiling $1 on Liunx
	gcc -DON_LINUX -D_REENTRANT -D__USE_POSIX199309 -D_GNU_SOURCE -o `basename $1 '.c'` $1 /home/courses/ele709/libdlab.a -lpthread -lrt -lm
else
	echo Simulation mode not supported
fi
echo Done.
