#!/bin/bash
if [ `uname -r` != 4.4.91-ti-r133 ]
then
	echo Hardware mode can be used on microcontroller in motor module only.
	exit 1;
else
	echo Compiling $1 in Hardware mode ...
	/usr/bin/gcc -DON_LINUX -D_REENTRANT -D__USE_POSIX199309 -D_GNU_SOURCE -o `basename $1 '.c'` $1 /usr/local/lib/libdlab.a -lpthread -lm -lrt
fi
echo Done.
