#!/bin/sh
#ps2jpg script by Ian Hutchinson 1998; use at your own risk.
#You need Ghostscript and the pbmplus utilities installed. 
if [ $# -lt 2 ] ; then
       echo " Usage: ps2jpg <file.ps> <file.jpg> [<icon.jpg>]" 1>&2
       exit 1
else 
#    echo "Calling ghostscript to convert, please wait ..." >&2
    filein=$1
    gs -sDEVICE=jpeg -sOutputFile=- -sNOPAUSE -q $filein -c showpage -c quit >$2
    shift 2
    if [ $# -eq 1 ] ;then
# Make an icon file.
       gs -sDEVICE=jpeg -sOutputFile=- -sNOPAUSE -q $filein -c showpage -c quit >$1
    fi
fi


